### ISSUE TITLE
Template app.config injection doesn't place the configSections element first

### ISSUE THREAD

**Issue by jcfarsight** [DbTestMonkey/DbTestMonkey#14]
An issue has been discovered where DbTestMonkey does not inject the 'configSections' configuration group as the first sub-element of the 'configuration' element.

In my example this meant that the 'startup' node appeared before the 'configSections' node which caused a System.Configuration.ConfigurationErrorsException to be throwing when running the tests inside the project.

We need to investigate the ordering of configuration elements and ensure we can correctly inject the sample nodes into the right place every time regardless of what existing configuration exists.

**Comment by DbTestMonkey** [comment]
Fixed in changeset 8701a4903ad747994d034136c485cfc857baac6f as part of release 2.0.2.
