### ISSUE TITLE
DbTestMonkey.XUnit.Fody.ClassDatabaseFixture and CollectionDatabaseFixture should implement IDisposable

### ISSUE THREAD

**Issue by jcfarsight** [DbTestMonkey/DbTestMonkey#15]
These classes have a public Dispose method as per the IDisposable interface but do not formally implement that interface.

This should change.

**Comment by DbTestMonkey** [comment]
Fixed in changeset 8701a4903ad747994d034136c485cfc857baac6f as part of release 2.0.2.
