### ISSUE TITLE
Update Fix-ReferencesCopyLocal from install.ps1 in XUnit.Fody project

### ISSUE THREAD

**Issue by jcfarsight** [DbTestMonkey/DbTestMonkey#16]
Because we have now introduced the ClassDatabaseFixture and CollectionDatabaseFixture classes to the DbTestMonkey.XUnit.Fody project, it is now a formal dependency to weaved test projects even though VS doesn't realise it.

We need to update the step to ensure it always copies the binary locally.

**Comment by DbTestMonkey** [comment]
Fixed in changeset 8701a4903ad747994d034136c485cfc857baac6f as part of release 2.0.2.
