### ISSUE TITLE
SqlServer Rapid Deploy can have issues with cross db dependencies when files are deleted

### ISSUE THREAD

**Issue by DbTestMonkey** [DbTestMonkey/DbTestMonkey#8]
Rapid Deploy Mode has safe guards and repair logic if:
a) Physical database file is deleted but logical database file remains.
b) Logical database is deleted by physical database file remains.
c) Both physical and logical database entities are deleted.

Unfortunately because databases are spawned up and populated one at a time, if one database references another that is in a broken state then it will fail to be populated.

The dropping and creation of databases, and creation of database schema actions need to be split up.

**Comment by jcfarsight** [comment]
Resolved in release 2.0.0 through change-set 53130bb3fb8dc0fc1b37cf3abda6b4e732846351.
